sudo: required
language: python
python:
  - "2.6"
  - "2.7"

install:
  - sudo bash util/install.sh

script:
  - cd test && sudo bash test_all_commands.sh

branches:
  only:
    - master
    - dev
